name: CI
on: [push]

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      
      - name: Run tsc
        uses: borales/actions-yarn@v4
        with:
          cmd: tsc

      - name: Build Backend
        uses: borales/actions-yarn@v4
        with:
          cmd: build:backend
      
      # - name: Log in to the Container registry
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: './'
          file: ./packages/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backstage:latest